server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://switernal.com:3306/mylibrary?useunicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false&serverTimezone=GMT%2B8
    username: mylibrary
    password: 2333
    driver-class-name: com.mysql.cj.jdbc.Driver